name: Create Github Release

on:
  push:
    branches: [ main ]

permissions: write-all
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
          cache: maven

      - name: Set version variable
        run: |
          echo "VERSION_NAME=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo Version found ${{env.VERSION_NAME}}
          
      - name: Building package with Maven [${{env.VERSION_NAME}}]
        run: |
          mvn -B clean package --file pom.xml
          
      - name: Create release (only non-snapshot versions)
        if: ${{ !endsWith(env.VERSION_NAME, '-SNAPSHOT') }}
        run: |
          if [ $(git tag -l "v${{env.VERSION_NAME}}") ]; then echo "Tag v${{env.VERSION_NAME}} already released"; exit 1; fi
          gh release create v${{env.VERSION_NAME}} -t v${{env.VERSION_NAME}} target/unhcr-erff-validation-tool-${{env.VERSION_NAME}}.jar target/unhcr-erff-validation-tool-${{env.VERSION_NAME}}-full.jar --latest --generate-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
